import { useState, useEffect } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import PageHeader from "../../components/PageHeader";
import Btn from "../../components/Btn";
import { Field, Input, Textarea, Select } from "../../components/Field";
import Spinner from "../../components/Spinner";
import { api } from "../../lib/api";

const ANALYSIS_OPTS = [
  { id: "ocr", label: "OCR Extraction", desc: "Extract text from scanned or handwritten documents" },
  { id: "ai", label: "AI Content Detection", desc: "Detect passages generated by AI tools" },
  { id: "similarity", label: "Similarity Check", desc: "Compare against all submissions in this assignment" },
  { id: "handwriting", label: "Handwriting Analysis", desc: "Analyse pen strokes for cross-student similarity" },
];

export default function CreateAssignment() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const preselectedTeam = searchParams.get("teamId");
  const [loading, setLoading] = useState(false);
  const [teamsLoading, setTeamsLoading] = useState(true);
  const [teams, setTeams] = useState<any[]>([]);
  const [title, setTitle] = useState("");
  const [team, setTeam] = useState(preselectedTeam || "");
  const [type, setType] = useState("pdf,docx,txt,png,jpg");
  const [dueDate, setDueDate] = useState("");
  const [dueTime, setDueTime] = useState("23:59");
  const [maxMarks, setMaxMarks] = useState("100");
  const [description, setDescription] = useState("");
  const [enabled, setEnabled] = useState<string[]>(["ocr", "ai", "similarity"]);
  const [aiThreshold, setAiThreshold] = useState("30");
  const [simThreshold, setSimThreshold] = useState("40");
  const [errors, setErrors] = useState<Record<string, string>>({});

  useEffect(() => {
    async function loadTeams() {
      try {
        const data = await api.teams.list();
        setTeams(data || []);
        if (preselectedTeam) {
          setTeam(preselectedTeam);
        } else if (data && data.length > 0 && !team) {
          setTeam(data[0].id);
        }
      } catch (err) {
        console.error("Failed to load teams", err);
      } finally {
        setTeamsLoading(false);
      }
    }
    loadTeams();
  }, [preselectedTeam]);

  function toggle(id: string) {
    setEnabled((prev) =>
      prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]
    );
  }

  function validate() {
    const e: Record<string, string> = {};
    if (!title.trim()) e.title = "Assignment title is required.";
    if (!team) e.team = "Please select a team.";
    if (!dueDate) e.dueDate = "Due date is required.";
    return e;
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    const errs = validate();
    if (Object.keys(errs).length) {
      setErrors(errs);
      return;
    }
    setLoading(true);

    try {
      let isoDueDate: string | undefined = undefined;
      if (dueDate) {
        isoDueDate = new Date(`${dueDate}T${dueTime || "23:59"}:00`).toISOString();
      }

      const created = await api.assignments.create(team, {
        title,
        description: description || undefined,
        due_date: isoDueDate,
        max_marks: parseFloat(maxMarks) || 100,
        allowed_file_types: type,
      });

      // Save grading configuration with configured thresholds
      if (created?.id) {
        try {
          await api.grading.saveConfig(created.id, {
            criteria: [
              { name: "Originality & Authenticity", weight: 0.5, description: "Evaluated by AI & Similarity engine" },
              { name: "Subject Mastery & Content", weight: 0.5, description: "Content quality and depth" },
            ],
            rules: [
              { rule_type: "ai_threshold", threshold: parseFloat(aiThreshold) || 30, penalty_marks: 10, action: "flag" },
              { rule_type: "similarity_threshold", threshold: parseFloat(simThreshold) || 40, penalty_marks: 15, action: "flag" },
            ],
          });
        } catch {
          // Non-blocking if grading config endpoint optional
        }
      }

      navigate("/teacher/assignments");
    } catch (err: any) {
      setErrors({ form: err?.message || "Failed to create assignment. Please try again." });
    } finally {
      setLoading(false);
    }
  }

  return (
    <div>
      <PageHeader
        title="Create Assignment"
        breadcrumbs={[{ label: "Assignments" }, { label: "New" }]}
        subtitle="Configure details and analysis parameters for this assessment."
      />
      <div style={{ maxWidth: 600 }}>
        <form onSubmit={handleSubmit} className="space-y-5">
          {errors.form && (
            <div
              className="p-3.5 rounded-xl text-sm"
              style={{
                background: "var(--color-red-bg)",
                border: "1px solid var(--color-red-border)",
                color: "var(--color-red)",
              }}
            >
              {errors.form}
            </div>
          )}

          {/* Details */}
          <section
            className="rounded-xl p-6 space-y-4"
            style={{ background: "var(--color-surface)", border: "1px solid var(--color-border)" }}
          >
            <p className="font-semibold" style={{ fontSize: 14, color: "var(--color-text-1)" }}>
              Details
            </p>
            <Field label="Assignment title" error={errors.title} required>
              <Input
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="e.g. Essay 1 — Research Methodology"
                error={!!errors.title}
              />
            </Field>
            <div className="grid grid-cols-2 gap-4">
              <Field label="Team" error={errors.team} required>
                {teamsLoading ? (
                  <div className="flex items-center gap-2 py-2 text-xs text-slate-400">
                    <Spinner size={14} color="var(--color-accent)" /> Loading teams…
                  </div>
                ) : (
                  <Select value={team} onChange={(e) => setTeam(e.target.value)}>
                    <option value="">Select team…</option>
                    {teams.map((t) => (
                      <option key={t.id} value={t.id}>
                        {t.name}
                      </option>
                    ))}
                  </Select>
                )}
              </Field>
              <Field label="Allowed file types">
                <Select value={type} onChange={(e) => setType(e.target.value)}>
                  <option value="pdf,docx,txt,png,jpg">All standard (PDF, Word, TXT, Images)</option>
                  <option value="pdf">PDF only</option>
                  <option value="docx,pdf">Documents (Word, PDF)</option>
                  <option value="png,jpg,jpeg">Handwritten Scans (Images)</option>
                </Select>
              </Field>
            </div>
            <div className="grid grid-cols-3 gap-4">
              <div className="col-span-2">
                <Field label="Due date" error={errors.dueDate} required>
                  <Input
                    type="date"
                    value={dueDate}
                    onChange={(e) => setDueDate(e.target.value)}
                    error={!!errors.dueDate}
                  />
                </Field>
              </div>
              <Field label="Time (24h)">
                <Input
                  type="time"
                  value={dueTime}
                  onChange={(e) => setDueTime(e.target.value)}
                  style={{ fontFamily: "var(--font-mono)" }}
                />
              </Field>
            </div>
            <Field label="Max marks">
              <Input
                type="number"
                value={maxMarks}
                onChange={(e) => setMaxMarks(e.target.value)}
                min="1"
                style={{ fontFamily: "var(--font-mono)", maxWidth: 120 }}
              />
            </Field>
            <Field label="Instructions">
              <Textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                rows={3}
                placeholder="Instructions or context visible to students…"
              />
            </Field>
          </section>

          {/* Analysis */}
          <section
            className="rounded-xl p-6 space-y-4"
            style={{ background: "var(--color-surface)", border: "1px solid var(--color-border)" }}
          >
            <div>
              <p className="font-semibold" style={{ fontSize: 14, color: "var(--color-text-1)" }}>
                Analysis Configuration
              </p>
              <p style={{ fontSize: 12.5, color: "var(--color-text-3)", marginTop: 2 }}>
                Select which analyses to run on all submitted work.
              </p>
            </div>
            <div className="space-y-2">
              {ANALYSIS_OPTS.map((opt) => (
                <label
                  key={opt.id}
                  className="flex items-start gap-3 p-3 rounded-lg cursor-pointer transition-colors"
                  style={{
                    border: `1px solid ${
                      enabled.includes(opt.id) ? "var(--color-accent)" : "var(--color-border)"
                    }`,
                    background: enabled.includes(opt.id) ? "var(--color-accent-bg)" : "var(--color-canvas)",
                  }}
                >
                  <input
                    type="checkbox"
                    checked={enabled.includes(opt.id)}
                    onChange={() => toggle(opt.id)}
                    style={{
                      accentColor: "var(--color-accent)",
                      marginTop: 2,
                      width: 14,
                      height: 14,
                      flexShrink: 0,
                    }}
                  />
                  <div>
                    <p
                      className="font-medium"
                      style={{
                        fontSize: 13,
                        color: enabled.includes(opt.id) ? "var(--color-accent)" : "var(--color-text-1)",
                      }}
                    >
                      {opt.label}
                    </p>
                    <p style={{ fontSize: 12, color: "var(--color-text-3)", marginTop: 2 }}>
                      {opt.desc}
                    </p>
                  </div>
                </label>
              ))}
            </div>

            {/* Thresholds */}
            <div
              className="pt-3 grid grid-cols-2 gap-4"
              style={{ borderTop: "1px solid var(--color-border)" }}
            >
              <Field label="AI flag threshold (%)" hint="Flag submissions scoring above this">
                <Input
                  type="number"
                  value={aiThreshold}
                  onChange={(e) => setAiThreshold(e.target.value)}
                  min="0"
                  max="100"
                  style={{ fontFamily: "var(--font-mono)" }}
                />
              </Field>
              <Field label="Similarity flag threshold (%)" hint="Flag matches above this">
                <Input
                  type="number"
                  value={simThreshold}
                  onChange={(e) => setSimThreshold(e.target.value)}
                  min="0"
                  max="100"
                  style={{ fontFamily: "var(--font-mono)" }}
                />
              </Field>
            </div>
          </section>

          <div className="flex gap-2.5 pt-2">
            <Btn
              variant="ghost"
              size="md"
              type="button"
              onClick={() => navigate("/teacher/assignments")}
            >
              Cancel
            </Btn>
            <Btn
              variant="primary"
              size="md"
              type="submit"
              loading={loading}
              style={{ flex: 1 }}
            >
              {loading ? "Creating assignment…" : "Create assignment"}
            </Btn>
          </div>
        </form>
      </div>
    </div>
  );
}
